source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/lookandfeel.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/windowrule.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/misc.conf
