splash = false
preload = /home/dovahkiin/wallpapers/floating-balloons-3440x1440.jpg
wallpaper = DP-3,/home/dovahkiin/wallpapers/floating-balloons-3440x1440.jpg
wallpaper = HDMI-A-1,/home/dovahkiin/wallpapers/floating-balloons-3440x1440.jpg
