env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


# 缩略图相关环境变量
#env = XDG_CURRENT_DESKTOP,Thunar
env = QT_QPA_PLATFORMTHEME,gtk3  # 如果使用 QT 应用
env = GTK_USE_PORTAL,1

# 缩略图缓存
env = XDG_CACHE_HOME,$HOME/.cache


# 中文环境变量设置
env = LANG,zh_CN.UTF-8
env = LANGUAGE,zh_CN:en_US
env = LC_CTYPE,zh_CN.UTF-8


#fcitx5
env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im,fcitx
env = INPUT_METHOD,fcitx
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,ibus  # 某些应用可能需要
